version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.3.8-buster
    steps:
      - checkout
      - restore_cache:
          keys:
            - wcbot-{{ checksum "composer.lock" }}
            - wcbot-
      - run: sed -i.bak "s/APP_ENV=dev/APP_ENV=${APP_MODE}/g" .env
      - run: sed -i.bak "s/{db_user}/${MYSQL_USER}/g" .env
      - run: sed -i.bak "s/{db_password}/${MYSQL_PASSWORD}/g" .env
      - run: sed -i.bak "s/{db_host}/${MYSQL_HOST}/g" .env
      - run: sed -i.bak "s/{db_port}/${MYSQL_PORT}/g" .env
      - run: sed -i.bak "s/{db_name}/${MYSQL_DBNAME}/g" .env
      - run: composer dump-env $APP_MODE
      - run: composer install -n --prefer-dist
      - run: sed -i.bak "s/{http_port}/${HTTP_PORT}/g" docker-compose.prod.yml
      - run: sed -i.bak "s/{mysql_root_pwd}/${MYSQL_ROOT_PWD}/g" docker-compose.prod.yml
      - run: sed -i.bak "s/{mysql_user}/${MYSQL_USER}/g" docker-compose.prod.yml
      - run: sed -i.bak "s/{mysql_password}/${MYSQL_PASSWORD}/g" docker-compose.prod.yml
      - save_cache:
          key: wcbot-{{ checksum "composer.lock" }}
          paths:
            - ./vendor
      - persist_to_workspace:
          root: .
          paths:
            - .
  # test:
  #   docker:
  #     - image: circleci/php:7.3.8-stretch
  deploy:
    docker:
      - image: circleci/buildpack-deps:buster
    steps:
      - attach_workspace:
          at: .
      - run: sudo apt update && sudo apt install rsync
      - run: 
          name: Deploying
          command: |
            rsync \
                -e "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" \
                -rzvI \
                --include vendor \
                --include .env.local.php \
                --exclude .git \
                --exclude .circleci \
                --exclude-from=".gitignore" \
                --exclude authorized_keys \
                . $REMOTE_USERNAME@$REMOTE_HOST:$REMOTE_PATH
      - run: ssh -o "StrictHostKeyChecking=no" $REMOTE_USERNAME@$REMOTE_HOST "cd ${REMOTE_PATH} && docker-compose down && docker-compose -f docker-compose.prod.yml build && docker-compose -f docker-compose.prod.yml up -d"

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
