version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.3.8-buster
    steps:
      - checkout
      - restore_cache:
          keys:
            - wcbot-{{ checksum "composer.lock" }}
            - wcbot-
      - run: composer install -n --prefer-dist
      - run: sed -i.bak "s/APP_ENV=dev/${APP_MODE}/g" .env
      - run: composer dump-env $APP_MODE
      - run: sed -i.bak "s/{http_port}/${HTTP_PORT}/g" docker-compose.prod.yml
      - run: sed -i.bak "s/{mysql_root_pwd}/${MYSQL_ROOT_PWD}/g" docker-compose.prod.yml
      - run: sed -i.bak "s/{mysql_user}/${MYSQL_USER}/g" docker-compose.prod.yml
      - run: sed -i.bak "s/{mysql_password}/${MYSQL_PASSWORD}/g" docker-compose.prod.yml
      - save_cache:
          key: wcbot-{{ checksum "composer.lock" }}
          paths:
            - ./vendor
      - persist_to_workspace:
          root: .
          paths:
            - .
  # test:
  #   docker:
  #     - image: circleci/php:7.3.8-stretch
  deploy:
    docker:
      - image: circleci/buildpack-deps:buster
    steps:
      - attach_workspace:
          at: .
      - run: ls -la
      - run: cat docker-compose.prod.yml

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
